### ISSUE TITLE
"Currently working at" is outdated

### ISSUE THREAD

**Issue by hgranillo** [edufortes/edufortes#1]
Dear Elduardo

I just noticed that your homepage displays that you are currently working at TTMzero, but this is not true anymore.

https://github.com/edufortes/edufortes/blob/main/README.md?plain=1#L6

I suggest to update that line in order to better reflect your current work place.

Worm regards

**Comment by hgranillo** [comment]
please respond

**Comment by maufranchini** [comment]
+1

**Comment by komodin** [comment]
+1

**Comment by edufortes** [comment]
Dear @hgranillo & @maufranchini 

This issue has been addressed on this particular [PR](https://github.com/edufortes/edufortes/pull/2)

**Comment by komodin** [comment]
thanks for solving it

**Comment by maxstreese** [comment]
+2
