### ISSUE TITLE
Incorrect Twitter (now X) references

### ISSUE THREAD

**Issue by hgranillo** [edufortes/edufortes#3]
Hello dear Elduardo

I've noticed that in the social links section of your README.md you have references to X previous name "Twitter".
Maybe you are not aware but the social network Twitter (now X), changed names a couple of years ago.

The use of Twitter instead of X could lead to misinterpretations and could be understood as a political manifestation against the change of ownership Twitter (now X) had in 2022. If this doesn't relate to any of that (I hope it's not the case) please update promptly.

edit: 
If its the case you are against the ownership of X (formerly Twitter), please update your social links to whatever mastodon network are you using or your bluesky (more like deadsky amirite?).

Worm regards

**Comment by maufranchini** [comment]
+1

**Comment by komodin** [comment]
Please fix it. Thanks.

**Comment by hgranillo** [comment]
@edufortes 

If its the case you are against the ownership of X (formerly Twitter), please update your social links to whatever mastodon network are you using or your bluesky (more like deadsky amirite?).

**Comment by hgranillo** [comment]
+2

**Comment by dancost** [comment]
This is a blocking issue. Please fix.

**Comment by edufortes** [comment]
Thanks for reporting it @hgranillo. 

We're working in your suggestions.

Worn Regards, L'Duardo.

**Comment by maxstreese** [comment]
Almost not a year since this CVE has been reported and still no movement. What the heck?

![image](https://github.com/user-attachments/assets/0f544903-53ea-42ee-b4c1-e23bca32c120)

**Comment by hgranillo** [comment]
Any ETA on this?

Thanks

**Comment by maufranchini** [comment]
pls respond

**Comment by komodin** [comment]
fix it please, urgently

**Comment by komodin** [comment]
Still waiting. Fix it ASAP. Thanks.

cc @maufranchini @hgranillo

**Comment by edufortes** [comment]
<iframe src="https://giphy.com/embed/l4FB4X7ovg3TUCM8w" width="480" height="360" style="" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/spongebob-spongebob-squarepants-episode-2-l4FB4X7ovg3TUCM8w">via GIPHY</a></p>

**Comment by edufortes** [comment]
Problem solved!

**Comment by komodin** [comment]
Thanks. Really appreciate it.
